#!/usr/bin/bash

# DESKTOPS
bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9 10

# CONFIGURATION
bspc config border_width 2
bspc config window_gap 0
# Causes flickering.
# bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color "#eee8d5"  # Solarized Base2
bspc config focused_border_color "#859900"  # Solarized Green
bspc config presel_feedback_color "#2aa198"  # Solarized Cyan

# Add top padding for polybar.
bspc config top_padding 20

# PROGRAM RULES
bspc rule --add KeePassXC state=floating
bspc rule --add Peek state=floating
bspc rule --add Zathura state=tiled

# PROGRAMS
killall --quiet sxhkd || true; sxhkd &
killall --quiet polybar || true; polybar top > /tmp/polybar.log 2>&1 &
killall --quiet picom && sleep 0.1 || true; picom &
killall --quiet dunst || true; dunst &
killall --quiet blueman-applet || true; blueman-applet
